[theme]
primaryColor = "#F63366"   # The "Accent" color (Sliders, Buttons)
backgroundColor = "#FFFFFF" # Main area background
secondaryBackgroundColor = "#F0F2F6" # Sidebar background
textColor = "#262730"       # Text color
font = "sans serif"